# Generated by Django 5.2.9 on 2026-02-28 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_programmer_address_programmer_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='pending_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Kutilmoqda'), ('TODO', 'Bugun uchun'), ('DONE', 'Bajarildi'), ('APPROVED', 'Tasdiqlandi'), ('REJECTED', 'Rad etildi')], default='TODO', max_length=20),
        ),
    ]
