# Generated by Django 5.2.9 on 2026-02-28 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_pending_at_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='queue_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
